runtime: python27
api_version: 1
threadsafe: yes

handlers:
 - url: /
   static_files: dist/webmet/index.html
   upload: dist/webmet/index
 - url: /
   static_dir: dist/webmet

skip_files:
- e2e/
- node_modules/
- src/
- ^(.*/)?\..*$
- ^(.*/)?.*.json$
- ^(.*/)?.*.md$
- ^(.*/)?.*.yaml$
- ^LICENSE